shop/urls.py
from django.urls import path
from .views import *

app_name = 'shop'


urlpatterns = [
    path('product_detail/<slug:product_detail_slug>/', product_detail, name='product_detail'),
    path('profile/', profile, name='profile'),
    path('logout/', logout_profile, name='logout'),
    path('categories/', categories, name='categories'),
    path('cart_fetch/', cart_fetch),
    path('order/', order, name='order'),
    path('cart/', cart, name='cart'),
    path('', home, name='home'),
]

small_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'shop.views.page_not_found'

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Интернет магазин с товарами">
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/header.css' %}">
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <link rel="stylesheet" href="{% static 'css/product_detail.css' %}">
    <link rel="stylesheet" href="{% static 'css/categories.css' %}">
    <link rel="stylesheet" href="{% static 'css/profile.css' %}">
    <title>{{ title }}</title>
</head>
<body>

<div class="wrapper">
    {% include 'includes/header.html' %}
    <main class="main">
        {% block content %}{% endblock %}
    </main>
    <div class="product_added_container">
        <p class="text">Товар добавлен в корзину</p>
        <a href="{% url 'shop:cart' %}" class="link">Перейти в корзину</a>
    </div>
</div>

<script>
    let csrf_token = '{{ csrf_token }}';
</script>
<script src="{% static 'js/cart.js' %}"></script>
</body>
</html>

templates/cart.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <h1 class="cart_title">Корзина</h1>
    <div class="products">
        {% for product in products %}
            <card class="products__card" data-set-id="{{ product.product.id }}">
                <a href="{{ product.product.get_absolute_url }}" class="product_card">
                    <img src="{% static 'images/empty_image.png' %}" alt="Пустая картинка">
                    <h3 class="product_title">{{ product.product.name }}</h3>
                    <div class="cost">
                        {% if product.product.discount_price %}
                            <h3 class="price">
                                {{ product.product.discount_price }} руб.
                            </h3>
                            <h3 class="old_price old_price_with_discount">{{ product.product.price }} руб.</h3>
                        {% else %}
                            <h3 class="old_price">{{ product.product.price }} руб.</h3>
                        {% endif %}
                    </div>
                </a>
                <div class="product_count">
                    Количество:
                    <p class="product_count_value">{{ product.count }}</p>
                </div>
                <div class="cart_remove" data-set-id="{{ product.product.id }}">
                    <svg height="16" width="16" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M8.50033 19.6667C8.96056 19.6667 9.33366 19.2936 9.33366 18.8333C9.33366 18.3731 8.96056 18 8.50033 18C8.04009 18 7.66699 18.3731 7.66699 18.8333C7.66699 19.2936 8.04009 19.6667 8.50033 19.6667Z" stroke="#222222" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path><path d="M18.4993 19.6667C18.9596 19.6667 19.3327 19.2936 19.3327 18.8333C19.3327 18.3731 18.9596 18 18.4993 18C18.0391 18 17.666 18.3731 17.666 18.8333C17.666 19.2936 18.0391 19.6667 18.4993 19.6667Z" stroke="#222222" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path><path d="M1 1H4.63636L7.07273 12.9019C7.15586 13.3112 7.38355 13.6788 7.71595 13.9404C8.04835 14.202 8.46427 14.341 8.89091 14.333H17.7273C18.1539 14.341 18.5698 14.202 18.9022 13.9404C19.2346 13.6788 19.4623 13.3112 19.5455 12.9019L21 5.44434H5.54545" stroke="#222222" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path></svg>
                    <p class="title">Удалить</p>
                </div>
            </card>
        {% endfor %}
    </div>
    {% if request.user.is_authenticated and products %}
        <a href="{% url 'shop:order' %}" class="order_link">Перейти к оформлению</a>
    {% endif %}
{% endblock %}

templates/categories.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <ul class="categories__list">
        {% for cat in category %}
            <div class="category_block">
                <li class="list__item">
                    <a href="?category={{ cat.id }}" class="item__link">{{ cat.name }}</a>
                </li>
                {% if cat.subcategories %}
                    <ol class="subcategories__list">
                        {% for subcat in cat.subcategories.all %}
                            <li class="list__item list__item_subcategory">
                                <a href="?subcategory={{ subcat.id }}" class="item__link item__link_subcategory">{{ subcat.name }}</a>
                            </li>
                        {% endfor %}
                    </ol>
                {% endif %}
            </div>
        {% endfor %}
    </ul>
    {% if products %}
        <div class="products">
        {% for product in products %}
            <card class="products__card">
                <a href="{{ product.get_absolute_url }}" class="product_card">
                    <img src="{% static 'images/empty_image.png' %}" alt="Пустая картинка">
                    <h3 class="product_title">{{ product.name }}</h3>
                    <div class="cost">
                        {% if product.discount_price %}
                        <h3 class="price">
                            {{ product.discount_price }} руб.
                        </h3>
                        <h3 class="old_price old_price_with_discount">{{ product.price }} руб.</h3>
                        {% else %}
                            <h3 class="old_price">{{ product.price }} руб.</h3>
                        {% endif %}
                    </div>
                </a>
                <div class="cart_add" data-set-id="{{ product.id }}">
                    <svg height="16" width="16" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M8.50033 19.6667C8.96056 19.6667 9.33366 19.2936 9.33366 18.8333C9.33366 18.3731 8.96056 18 8.50033 18C8.04009 18 7.66699 18.3731 7.66699 18.8333C7.66699 19.2936 8.04009 19.6667 8.50033 19.6667Z" stroke="#222222" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path><path d="M18.4993 19.6667C18.9596 19.6667 19.3327 19.2936 19.3327 18.8333C19.3327 18.3731 18.9596 18 18.4993 18C18.0391 18 17.666 18.3731 17.666 18.8333C17.666 19.2936 18.0391 19.6667 18.4993 19.6667Z" stroke="#222222" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path><path d="M1 1H4.63636L7.07273 12.9019C7.15586 13.3112 7.38355 13.6788 7.71595 13.9404C8.04835 14.202 8.46427 14.341 8.89091 14.333H17.7273C18.1539 14.341 18.5698 14.202 18.9022 13.9404C19.2346 13.6788 19.4623 13.3112 19.5455 12.9019L21 5.44434H5.54545" stroke="#222222" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path></svg>
                    <p class="title">В корзину</p>
                </div>
            </card>
        {% endfor %}
    </div>
    {% endif %}
    {% if request_GET and not products %}
        <h2 class="not_found">Товаров по этой категории не найдено</h2>
    {% endif %}
{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="content_products">
        <div class="products">
            {% for product in page_obj %}
                <card class="products__card">
                    <a href="{{ product.get_absolute_url }}" class="product_card">
                        <img src="{% static 'images/empty_image.png' %}" alt="Пустая картинка">
                        <h3 class="product_title">{{ product.name }}</h3>
                        <div class="cost">
                            {% if product.discount_price %}
                            <h3 class="price">
                                {{ product.discount_price }} руб.
                            </h3>
                            <h3 class="old_price old_price_with_discount">{{ product.price }} руб.</h3>
                            {% else %}
                                <h3 class="old_price">{{ product.price }} руб.</h3>
                            {% endif %}
                        </div>
                    </a>
                    <div class="cart_add" data-set-id="{{ product.id }}">
                        <svg height="16" width="16" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M8.50033 19.6667C8.96056 19.6667 9.33366 19.2936 9.33366 18.8333C9.33366 18.3731 8.96056 18 8.50033 18C8.04009 18 7.66699 18.3731 7.66699 18.8333C7.66699 19.2936 8.04009 19.6667 8.50033 19.6667Z" stroke="#222222" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path><path d="M18.4993 19.6667C18.9596 19.6667 19.3327 19.2936 19.3327 18.8333C19.3327 18.3731 18.9596 18 18.4993 18C18.0391 18 17.666 18.3731 17.666 18.8333C17.666 19.2936 18.0391 19.6667 18.4993 19.6667Z" stroke="#222222" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path><path d="M1 1H4.63636L7.07273 12.9019C7.15586 13.3112 7.38355 13.6788 7.71595 13.9404C8.04835 14.202 8.46427 14.341 8.89091 14.333H17.7273C18.1539 14.341 18.5698 14.202 18.9022 13.9404C19.2346 13.6788 19.4623 13.3112 19.5455 12.9019L21 5.44434H5.54545" stroke="#222222" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path></svg>
                        <p class="title">В корзину</p>
                    </div>
                </card>
            {% endfor %}
        </div>
        <aside class="filter">
            <a href="?filter=true" class="filter_btn min_price_product">Фильтр</a>
        </aside>
    </div>
    {% if page_obj.has_other_pages %}
        <div class="paginator">
            <ul class="paginator__list">
                {% if page_obj.has_previous %}
                    <li class="list__item"><a href="?page={{ page_obj.previous_page_number }}">&lt;</a></li>
                {% endif %}
                {% for p in page_obj.paginator.page_range %}
                    {% if page_obj.number == p %}
                        <li class="list__item list__item_active"><a href="?page={{ p }}">{{ p }}</a></li>
                    {% elif p >= page_obj.number|add:-2 and p <= page_obj.number|add:2 %}
                         <li class="list__item"><a href="?page={{ p }}">{{ p }}</a></li>
                    {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                    <li class="list__item"><a href="?page={{ page_obj.next_page_number }}">&gt;</a></li>
                {% endif %}
            </ul>
        </div>
    {% endif %}
    {% if total_remainder %}
        <div class="products">
            <card class="products__card">
                <p>Самый дорогой</p>
                <a href="{{ max_price_product.get_absolute_url }}" class="product_card">
                    <img src="{% static 'images/empty_image.png' %}" alt="Пустая картинка">
                    <h3 class="product_title">{{ max_price_product.name }}</h3>
                    <div class="cost">
                        {% if max_price_product.discount_price %}
                        <h3 class="price">
                            {{ max_price_product.discount_price }} руб.
                        </h3>
                        <h3 class="old_price old_price_with_discount">{{ max_price_product.price }} руб.</h3>
                        {% else %}
                            <h3 class="old_price">{{ max_price_product.price }} руб.</h3>
                        {% endif %}
                    </div>
                </a>
                <div class="cart_add" data-set-id="{{ max_price_product.id }}">
                    <svg height="16" width="16" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M8.50033 19.6667C8.96056 19.6667 9.33366 19.2936 9.33366 18.8333C9.33366 18.3731 8.96056 18 8.50033 18C8.04009 18 7.66699 18.3731 7.66699 18.8333C7.66699 19.2936 8.04009 19.6667 8.50033 19.6667Z" stroke="#222222" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path><path d="M18.4993 19.6667C18.9596 19.6667 19.3327 19.2936 19.3327 18.8333C19.3327 18.3731 18.9596 18 18.4993 18C18.0391 18 17.666 18.3731 17.666 18.8333C17.666 19.2936 18.0391 19.6667 18.4993 19.6667Z" stroke="#222222" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path><path d="M1 1H4.63636L7.07273 12.9019C7.15586 13.3112 7.38355 13.6788 7.71595 13.9404C8.04835 14.202 8.46427 14.341 8.89091 14.333H17.7273C18.1539 14.341 18.5698 14.202 18.9022 13.9404C19.2346 13.6788 19.4623 13.3112 19.5455 12.9019L21 5.44434H5.54545" stroke="#222222" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path></svg>
                    <p class="title">В корзину</p>
                </div>
            </card>
            <card class="products__card">
            <p>Самый дешевый</p>
                <a href="{{ min_price_product.get_absolute_url }}" class="product_card">
                    <img src="{% static 'images/empty_image.png' %}" alt="Пустая картинка">
                    <h3 class="product_title">{{ min_price_product.name }}</h3>
                    <div class="cost">
                        {% if min_price_product.discount_price %}
                        <h3 class="price">
                            {{ min_price_product.discount_price }} руб.
                        </h3>
                        <h3 class="old_price old_price_with_discount">{{ min_price_product.price }} руб.</h3>
                        {% else %}
                            <h3 class="old_price">{{ min_price_product.price }} руб.</h3>
                        {% endif %}
                    </div>
                </a>
                <div class="cart_add" data-set-id="{{ min_price_product.id }}">
                    <svg height="16" width="16" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M8.50033 19.6667C8.96056 19.6667 9.33366 19.2936 9.33366 18.8333C9.33366 18.3731 8.96056 18 8.50033 18C8.04009 18 7.66699 18.3731 7.66699 18.8333C7.66699 19.2936 8.04009 19.6667 8.50033 19.6667Z" stroke="#222222" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path><path d="M18.4993 19.6667C18.9596 19.6667 19.3327 19.2936 19.3327 18.8333C19.3327 18.3731 18.9596 18 18.4993 18C18.0391 18 17.666 18.3731 17.666 18.8333C17.666 19.2936 18.0391 19.6667 18.4993 19.6667Z" stroke="#222222" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path><path d="M1 1H4.63636L7.07273 12.9019C7.15586 13.3112 7.38355 13.6788 7.71595 13.9404C8.04835 14.202 8.46427 14.341 8.89091 14.333H17.7273C18.1539 14.341 18.5698 14.202 18.9022 13.9404C19.2346 13.6788 19.4623 13.3112 19.5455 12.9019L21 5.44434H5.54545" stroke="#222222" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path></svg>
                    <p class="title">В корзину</p>
                </div>
            </card>
            <h2 class="summ_remains">Сумма остатков товаров:{{ total_remainder }}</h2>
        </div>
    {% endif %}
{% endblock %}

templates/includes/header.html
<header class="header">
    <nav class="navigation">
        <ul class="navigation__list">
            <li class="list__item">
                <a href="{% url 'shop:home' %}" class="item__link">Главная</a>
            </li>
            <li class="list__item">
                <a href="{% url 'shop:categories' %}" class="item__link">Категории</a>
            </li>
            <li class="list__item">
                {% if request.user.is_authenticated %}
                    <a href="{% url 'shop:profile' %}" class="item__link">Профиль</a>
                    {% else %}
                    <a href="{% url 'shop:profile' %}" class="item__link">Авторизация</a>
                {% endif %}
            </li>
            <li class="list__item list__item_cart">
                <a href="{% url 'shop:cart' %}" class="item__link">Корзина</a>
            </li>
        </ul>
    </nav>
</header>

templates/order.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="products">
        {% for product in products %}
            <card class="products__card" data-set-id="{{ product.product.id }}">
                <a href="{{ product.product.get_absolute_url }}" class="product_card">
                    <img src="{% static 'images/empty_image.png' %}" alt="Пустая картинка">
                    <h3 class="product_title">{{ product.product.name }}</h3>
                    <div class="cost">
                        {% if product.product.discount_price %}
                            <h3 class="price">
                                {{ product.product.discount_price }} руб.
                            </h3>
                        {% else %}
                            <h3 class="old_price">{{ product.product.price }} руб.</h3>
                        {% endif %}
                    </div>
                </a>
                <div class="product_count">
                    Количество:
                    <p class="product_count_value">{{ product.count }}</p>
                </div>
            </card>
        {% endfor %}
    </div>
    {% if products %}
        <aside class="order">
            <form action="" class="order_form" method="post">
                {% csrf_token %}
                <input type="submit" class="order_form_submit" value="Оформить заказ">
            </form>
        </aside>
    {% else %}
        <h1 class="not_found_products">Продуктов в корзине не найдено</h1>
    {% endif %}

{% endblock %}

templates/product_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="product_detail">
        <div class="product_info">
            <img src="{% static 'images/empty_image.png' %}" alt="Пустая картинка">
            <h2 class="product_name">{{ product.name }}</h2>
            <h3 class="product_price">
                {% if product.discount_price %}
                    {{ product.discount_price }} руб.
                {% else %}
                    {{ product.price }} руб.
                {% endif %}
            </h3>
        </div>
        <ul class="product_characteristics__list">
            {% for item in product.characteristicvalue_set.all %}
                <li class="list__item">
                    <p class="item_characteristic">{{ item.characteristic }}:</p>
                    <p class="item_value">{{ item.value }}</p>
                </li>
            {% endfor %}
        </ul>

    </div>
{% endblock %}

templates/profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    {% if not request.user.is_authenticated %}
        <form action="" method="post" class="form_login">
            {% csrf_token %}
            {{ login_form.as_div }}
            <button type="submit" class="submit_button">Авторизоваться</button>
        </form>
    {% else %}
        <h2 class="name">Добро пожаловать, {{ request.user.username }}</h2>
        <a href="{% url 'shop:logout' %}" class="logout">Выйти</a>
    {% endif %}
{% endblock %}